In [1]:
import pandas as pd

In [3]:
file_path = r'C:\ITStudy\101_TeamProject\Ship-Word-Challenge\성현\Code\make_test_set\eng_word_fixed.csv'
df = pd.read_csv(file_path, sep='|', encoding='utf-8')
df

,영단어,한국단어,설명
0,(Bulbous)Bow Warning Light,구상선수 주의등,구상선수가 있음을 알리기 위하여 켜는 선수등으로 적색 또는 청색이 있음
1,0.50% Sulphur limit,연료유 0.5% 황 함유량 규제,"0.50% Sulphur limit under MARPOL Annex VI, 선박에..."
2,2nd GENERATION INTACT STABLILITY,2세대 비손상 복원성,NaN
3,2010 HNS Protocol,2010년 위험 유해물질의 해상운송에 따른,‘위험·유해 물질의 해상운송에 따른 손해배상책임에 관한 국제협약’(Internati...
4,2010 Manila Amendments,2010 마닐라 개정,"2010년 6월에 필리핀 마닐라에서 열린 외교 회의에서 채택되었 으며, 선원들이 기..."
...,...,...,...
8123,standard Deviation,표준편차,평균값과의 편차들을 제곱한 값들의 평균값의 제곱근
8124,steam Radiator,증기방열기,증기난방에 사용되는 방열기
8125,steerage Passenger,보통선객,독방을 차지하지 않는 가장 싼 운임의 여객
8126,working Conditions,작업 여건(作業與件),NaN
8127,①Cross Section ②Transverse Plan,횡단면,①물체를 가로 자른 단면 ②선체를 기선에 수직한 면으로 자른 모양

In [4]:
df_c = df.drop(columns=['설명'])
df_c

                                   영단어                     한국단어
0           (Bulbous)Bow Warning Light                 구상선수 주의등
1                  0.50% Sulphur limit        연료유 0.5% 황 함유량 규제
2     2nd GENERATION INTACT STABLILITY              2세대 비손상 복원성
3                    2010 HNS Protocol  2010년 위험 유해물질의 해상운송에 따른
4               2010 Manila Amendments              2010 마닐라 개정
...                                ...                      ...
8123                standard Deviation                     표준편차
8124                    steam Radiator                    증기방열기
8125                steerage Passenger                     보통선객
8126                working Conditions              작업 여건(作業與件)
8127   ①Cross Section ②Transverse Plan                      횡단면

[8128 rows x 2 columns]

In [6]:
df_c.to_csv(r'C:\ITStudy\101_TeamProject\Ship-Word-Challenge\성현\Data\only_eng_kor_word.csv', index=False)